version: '3.8'
services:
  postgres:
    image: postgres:17
    container_name: finance-track-postgres
    restart: on-failure:5
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: my_database
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
