import { Category } from '@prisma/client';

export const getDefaultCategories = (
  userId: string,
  groupId?: string,
): Omit<Category, 'id' | 'createAt' | 'updateAt'>[] => [
  {
    name: 'Супермаркеты',
    categoryType: 'EXPENSE',
    userId,
    defaultKey: 'supermarket',
    ...(groupId && { groupId }),
  },
  {
    name: 'Кафе/Рестораны',
    categoryType: 'EXPENSE',
    userId,
    defaultKey: 'cafe',
    ...(groupId && { groupId }),
  },
  {
    name: 'Транспорт',
    categoryType: 'EXPENSE',
    userId,
    defaultKey: 'transport',
    ...(groupId && { groupId }),
  },
  {
    name: 'Дом/квартира',
    categoryType: 'EXPENSE',
    userId,
    defaultKey: 'home',
    ...(groupId && { groupId }),
  },
  {
    name: 'Здоровье',
    categoryType: 'EXPENSE',
    userId,
    defaultKey: 'health',
    ...(groupId && { groupId }),
  },
  {
    name: 'Образование',
    categoryType: 'EXPENSE',
    userId,
    defaultKey: 'education',
    ...(groupId && { groupId }),
  },
  {
    name: 'Развлечения',
    categoryType: 'EXPENSE',
    userId,
    defaultKey: 'entertainment',
    ...(groupId && { groupId }),
  },
  {
    name: 'Одежда/обувь',
    categoryType: 'EXPENSE',
    userId,
    defaultKey: 'clothes',
    ...(groupId && { groupId }),
  },
  {
    name: 'Связь/интернет/подписки',
    categoryType: 'EXPENSE',
    userId,
    defaultKey: 'communication',
    ...(groupId && { groupId }),
  },
  {
    name: 'Подарки',
    categoryType: 'EXPENSE',
    userId,
    defaultKey: 'expenseGifts',
    ...(groupId && { groupId }),
  },
  {
    name: 'Путешествия',
    categoryType: 'EXPENSE',
    userId,
    defaultKey: 'travel',
    ...(groupId && { groupId }),
  },
  {
    name: 'Авто',
    categoryType: 'EXPENSE',
    userId,
    defaultKey: 'auto',
    ...(groupId && { groupId }),
  },
  {
    name: 'Спорт',
    categoryType: 'EXPENSE',
    userId,
    defaultKey: 'sport',
    ...(groupId && { groupId }),
  },
  {
    name: 'Домашние питомцы',
    categoryType: 'EXPENSE',
    userId,
    defaultKey: 'pets',
    ...(groupId && { groupId }),
  },
  {
    name: 'Другое',
    categoryType: 'EXPENSE',
    userId,
    defaultKey: 'expenseOther',
    ...(groupId && { groupId }),
  },
  {
    name: 'Зарплата',
    categoryType: 'INCOME',
    userId,
    defaultKey: 'salary',
    ...(groupId && { groupId }),
  },
  {
    name: 'Подработка',
    categoryType: 'INCOME',
    userId,
    defaultKey: 'part-time',
    ...(groupId && { groupId }),
  },
  {
    name: 'Подарки',
    categoryType: 'INCOME',
    userId,
    defaultKey: 'incomeGifts',
    ...(groupId && { groupId }),
  },
  {
    name: 'Другое',
    categoryType: 'INCOME',
    userId,
    defaultKey: 'incomeOther',
    ...(groupId && { groupId }),
  },
];
