import { Category } from '@prisma/client';

export const getDefaultCategories = (
  userId: string,
  groupId?: string,
): Omit<Category, 'id' | 'createAt' | 'updateAt'>[] => [
  {
    name: 'Супермаркеты',
    categoryType: 'EXPENSE',
    userId,
    defaultKey: 'supermarket',
    color: '#4CAF50',
    icon: 'ShoppingCart',
    ...(groupId && { groupId }),
  },
  {
    name: 'Кафе/Рестораны',
    categoryType: 'EXPENSE',
    userId,
    defaultKey: 'cafe',
    color: '#FF7043',
    icon: 'Utensils',
    ...(groupId && { groupId }),
  },
  {
    name: 'Транспорт',
    categoryType: 'EXPENSE',
    userId,
    defaultKey: 'transport',
    color: '#42A5F5',
    icon: 'Bus',
    ...(groupId && { groupId }),
  },
  {
    name: 'Дом/квартира',
    categoryType: 'EXPENSE',
    userId,
    defaultKey: 'home',
    color: '#8D6E63',
    icon: 'Home',
    ...(groupId && { groupId }),
  },
  {
    name: 'Здоровье',
    categoryType: 'EXPENSE',
    userId,
    defaultKey: 'health',
    color: '#EF5350',
    icon: 'HeartPulse',
    ...(groupId && { groupId }),
  },
  {
    name: 'Образование',
    categoryType: 'EXPENSE',
    userId,
    defaultKey: 'education',
    color: '#7E57C2',
    icon: 'GraduationCap',
    ...(groupId && { groupId }),
  },
  {
    name: 'Развлечения',
    categoryType: 'EXPENSE',
    userId,
    defaultKey: 'entertainment',
    color: '#AB47BC',
    icon: 'Gamepad2',
    ...(groupId && { groupId }),
  },
  {
    name: 'Одежда/обувь',
    categoryType: 'EXPENSE',
    userId,
    defaultKey: 'clothes',
    color: '#26A69A',
    icon: 'Shirt',
    ...(groupId && { groupId }),
  },
  {
    name: 'Связь/интернет/подписки',
    categoryType: 'EXPENSE',
    userId,
    defaultKey: 'communication',
    color: '#29B6F6',
    icon: 'Smartphone',
    ...(groupId && { groupId }),
  },
  {
    name: 'Подарки',
    categoryType: 'EXPENSE',
    userId,
    defaultKey: 'expenseGifts',
    color: '#EC407A',
    icon: 'Gift',
    ...(groupId && { groupId }),
  },
  {
    name: 'Путешествия',
    categoryType: 'EXPENSE',
    userId,
    defaultKey: 'travel',
    color: '#26C6DA',
    icon: 'Plane',
    ...(groupId && { groupId }),
  },
  {
    name: 'Авто',
    categoryType: 'EXPENSE',
    userId,
    defaultKey: 'auto',
    color: '#78909C',
    icon: 'Car',
    ...(groupId && { groupId }),
  },
  {
    name: 'Спорт',
    categoryType: 'EXPENSE',
    userId,
    defaultKey: 'sport',
    color: '#66BB6A',
    icon: 'Dumbbell',
    ...(groupId && { groupId }),
  },
  {
    name: 'Домашние питомцы',
    categoryType: 'EXPENSE',
    userId,
    defaultKey: 'pets',
    color: '#FFB300',
    icon: 'PawPrint',
    ...(groupId && { groupId }),
  },
  {
    name: 'Другое',
    categoryType: 'EXPENSE',
    userId,
    defaultKey: 'expenseOther',
    color: '#9E9E9E',
    icon: 'MoreHorizontal',
    ...(groupId && { groupId }),
  },

  // INCOME

  {
    name: 'Зарплата',
    categoryType: 'INCOME',
    userId,
    defaultKey: 'salary',
    color: '#43A047',
    icon: 'Wallet',
    ...(groupId && { groupId }),
  },
  {
    name: 'Подработка',
    categoryType: 'INCOME',
    userId,
    defaultKey: 'part-time',
    color: '#66BB6A',
    icon: 'Briefcase',
    ...(groupId && { groupId }),
  },
  {
    name: 'Подарки',
    categoryType: 'INCOME',
    userId,
    defaultKey: 'incomeGifts',
    color: '#FFCA28',
    icon: 'Gift',
    ...(groupId && { groupId }),
  },
  {
    name: 'Другое',
    categoryType: 'INCOME',
    userId,
    defaultKey: 'incomeOther',
    color: '#9E9E9E',
    icon: 'MoreHorizontal',
    ...(groupId && { groupId }),
  },
];
